import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { RootState } from "@/lib/redux/store";
import ReduxProvider from "@/app/provider";

import SideBar from "@/components/layout/SideBar";
import Header from "@/components/layout/Header";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const authData = await getAuth();
  const initialState: Partial<RootState> = {
    // auth: authData,
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider initialState={initialState}>
          <SidebarProvider>
            <div className="w-screen h-dvh flex bg-background text-background-foreground">
                <SideBar />
              <div className="flex-1 h-full relative">
                <Header />
                <div className="pt-14 px-4">{children}</div>
              </div>
            </div>
          </SidebarProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
