import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/layout/SideBar";
import Header from "@/components/layout/Header";

import { RootState } from "@/lib/redux/store";
import ReduxProvider from "@/app/provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const authData = await getAuth();
  const initialState: Partial<RootState> = {
    // auth: authData,
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider initialState={initialState}>
          <div className="w-screen h-dvh flex bg-background text-background-foreground">
            <div className="w-64 h-full border-r border-border">
              <SideBar />
            </div>
            <div className="flex-1 h-full p-4 relative">
              <Header />
              <div className="pt-14">{children}</div>
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
